Final Merge
virtual-labs/exp-venturi-meter-iiith pull request #11
Opened 2021-04-08 04:10 UTC by vjspranav

A working simulation final merge into main

2021-04-10 15:46 UTC, raj-vlabs commented on experiment/references.md
> +- [The constructor](http://theconstructor.org/)
Please use https links exclusively

2021-04-10 15:48 UTC, raj-vlabs reviewed
1. Rename startAn to use a more meaningful name.
2. Use only https links

2021-04-12 12:23 UTC, vjspranav commented
> 1. Rename startAn to use a more meaningful name.
> 2. Use only https links

Have done the suggested, Please confirm and merge.
Thank You.

2021-04-13 17:09 UTC, raj-vlabs requested changes
1. Multiple extra spaces at the end of questions and options in both pretest.json and posttest.json.
2. Missing declaration for flags in main.js

2021-04-13 17:09 UTC, raj-vlabs commented on experiment/simulation/js/main.js
> +    flags = [true, true];
Where's flags declaration?

2021-04-13 17:09 UTC, raj-vlabs commented on experiment/pretest.json
> + ]
Multiple extra spaces at the end of questions and options.

2021-04-13 17:09 UTC, raj-vlabs commented on experiment/posttest.json
> + ]
Multiple extra spaces at the end of questions and options.

2021-04-14 03:07 UTC, raj-vlabs requested changes
1. Extra spaces still not removed from pretest.json
2. Undeclared variables ids and tube_ids and unused variable disablestart

2021-04-14 03:07 UTC, raj-vlabs commented on experiment/simulation/js/main.js
> +disablestart = false;
Unused variable.

2021-04-14 03:07 UTC, raj-vlabs commented on experiment/simulation/js/main.js
> +tube_ids = ["first-tube", "second-tube"];
Both variables ids and tube_ids undeclared.

2021-05-25 18:26 UTC, merged